import Section from "../../components/Section";
import { useCallback, useEffect, useState } from "react";
import { getWatch } from "../../fetch";
import { useRouter } from "next/router";
import Iframe from "react-iframe";
import Button from "../../components/Button";
import Head from "next/head";

function Watch() {
  const { query, isReady } = useRouter();
  const [result, setResult] = useState({});
  const [loading, setLoading] = useState(false);

  const getData = useCallback(async (slug) => {
    setLoading(true);
    const data = await getWatch(slug);
    setResult(data);
    setLoading(false);
  }, []);

  useEffect(() => {
    if (isReady) {
      getData(query.slug);
    }
  }, [getData, query.slug, isReady]);

  console.log(result);

  return (
    <>
      <Head>
        <title>Streaming {result.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        {loading && <h1>Loading....</h1>}
        <div>
          <Iframe
            url={result.video_uri}
            height="300px"
            id="myId"
            className="w-full"
            display="initial"
            position="relative"
          />
          <h1 className="text-lg text-gray-700 font-semibold mt-3">
            {result.title}
          </h1>
          <div className="mt-5 flex items-center justify-between">
            <Button
              backgroundColor="bg-gray-700"
              text="Previous"
              href={`/watch/${result.prev_eps}`}
            />
            <Button
              backgroundColor="bg-blue-500"
              text="Next"
              href={`/watch/${result.next_eps}`}
            />
          </div>
        </div>
      </Section>
    </>
  );
}

export default Watch;
