import Head from "next/head";
import AboutMe from "../../components/AboutMe";
import Header from "../../components/Header";
import Section from "../../components/Section";

function About() {
  return (
    <>
      <Head>
        <title>Tentang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Header />
        <AboutMe />
      </Section>
    </>
  );
}

export default About;
