import Head from "next/head";
import Info from "../components/Info";
import Section from "../components/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>Selamat Marathon One Piece</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Info />
      </Section>
    </>
  );
}
