import Head from "next/head";
import Section from "../../components/Section";
import { useEffect, useState } from "react";
import Link from "next/link";
import moment from "moment";
import Header from "../../components/Header";

function Bookmark() {
  const [bookmarks, setBookmarks] = useState([]);

  useEffect(() => {
    const sv = window.localStorage.getItem("saved");
    setBookmarks(JSON.parse(sv));
  }, []);

  console.log(bookmarks);

  return (
    <>
      <Head>
        <title>Bookmark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Header />
        <h1 className="text-lg text-gray-700 font-semibold">
          Yang kamu simpan
        </h1>
        <div className="mt-6 flex flex-col space-y-2 divide-y">
          {bookmarks?.map((bookmark, i) => (
            <Link href={`/watch/${bookmark.slug}`} key={i}>
              <a className="flex items-end justify-between cursor-pointer hover:bg-gray-100">
                <div className="flex flex-col space-y-1">
                  <h4 className="text-gray-700 font-bold">{bookmark.title}</h4>
                  <span className="text-xs">
                    {moment(bookmark.timestamp).format("LL")}
                  </span>
                </div>
              </a>
            </Link>
          ))}
        </div>
      </Section>
    </>
  );
}

export default Bookmark;
